package com.example.sudoku;

public enum CubeTypes {

	TOPLEFT_11, TOPMIDDLE_12, TOPRIGHT_13,

	MIDDLELEFT_21, MIDDLEMIDDLE_22, MIDDLERIGHT_23,

	BOTTOMLEFT_31, BOTTOMMIDDLE_32, BOTTOMRIGHT_33,
}
